[package]
name = "frontend"
version = "0.1.0"
authors = ["Cole Trammer <cole.trammer@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.18"

[dependencies]
seed = "0.9.1"