[package]
name = "poker_calculator"
version = "0.1.0"
authors = ["Cole Trammer <cole.trammer@gmail.com>"]
edition = "2021"

[workspace]
members = ["backend", "frontend"]

[dependencies]
itertools = "0.10.5"
